version: '3.8'

services:
  
  db:
    image: postgres:12
    container_name: database_postgres_PSBD
    environment:
      POSTGRES_DB: ticketsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  


volumes:
  pgdata:
    driver: local

